spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://127.0.0.1:50001/test
      auto-index-creation: true
logging:
  file:
    max-size: 20MB
    max-history: 10
    path: logs

storage:
  bulk-upload-path: uploads/files

upload-file:
  max-disk-usage-per-part: 50000
  max-parts: 2